Repository OCA/business-requirement, pull requests merged in 2018-09, with the labels that each got.

#287 [FIX] Weblate set up
  .travis.yml
Labels: needs review

#286 [FIX] Weblate set up
  .travis.yml
Labels: needs review

#285 [FIX] Weblate set up
  .travis.yml
Labels: needs review

#284 [FIX]Weblate setup
  .travis.yml
Labels: needs review

#283 [MIG] migration business_requirement_resource_template categ_id from 8.0 to 10.0
  .travis.yml
  business_requirement/README.rst
  business_requirement/models/business.py
  business_requirement/tests/test_br.py
  business_requirement_deliverable/README.rst
  business_requirement_deliverable/security/ir.model.access.csv
  business_requirement_deliverable_project/models/business.py
  business_requirement_deliverable_project_task_categ/README.rst
  business_requirement_deliverable_project_task_categ/__manifest__.py
  business_requirement_deliverable_project_task_categ/migrations/10.0.1.0.1/post-migration.py
  business_requirement_deliverable_resource_template_categ/README.rst
  business_requirement_deliverable_resource_template_categ/__manifest__.py
  business_requirement_deliverable_resource_template_categ/migrations/10.0.1.1.0/post-migration.py
  business_requirement_etherpad/__manifest__.py
Labels: approved, needs review

#293 [10.0][FIX][I276] Fix the onchange function of uom
  business_requirement_deliverable_cost/models/business.py
Labels: approved, needs review

#292 [10.0][FIX] Error when generating project
  business_requirement_deliverable_project/wizard/generate_projects.py
Labels: approved

#278 [ADD]business_requirement_earned_value
  business_requirement/views/business_view.xml
  business_requirement_deliverable_project_task_categ/data/business_requirement_deliverable_project_task_categ_demo.xml
  business_requirement_earned_value/README.rst
  business_requirement_earned_value/__init__.py
  business_requirement_earned_value/__manifest__.py
  business_requirement_earned_value/demo/project_completion_report_demo.xml
  business_requirement_earned_value/i18n/sl.po
  business_requirement_earned_value/models/__init__.py
  business_requirement_earned_value/models/br_and_project_inherit_function.py
  business_requirement_earned_value/report/__init__.py
  business_requirement_earned_value/report/br_earned_value_report.py
  business_requirement_earned_value/report/br_earned_value_report_view.xml
  business_requirement_earned_value/report/project_completion_report.py
  business_requirement_earned_value/report/project_completion_report_view.xml
  business_requirement_earned_value/security/ir.model.access.csv
  business_requirement_earned_value/static/img/correct_report.png
  business_requirement_earned_value/tests/__init__.py
  business_requirement_earned_value/tests/test_report_services.py
  business_requirement_earned_value/views/br_and_project_inherit_view.xml
  business_requirement_gap_analysis_task/data/gap_analysis_task_demo.xml
Labels: approved, needs review
